
GET http://localhost:4000/api/task

####

POST http://localhost:4000/api/task
Content-Type: application/json

{
  "title": "Descongelar el pollo",
  "description": "Descripción de la nueva tarea",
  "isComplete": false,
  "user_id": 2
}
####
PUT http://localhost:4000/api/task/1
Content-Type: application/json

{
  "title": "cocinar",
  "description": "Descongelar el pollo ",
  "isComplete": false,
  "user_id": 1
}
####
GET http://localhost:4000/api/task/1

####
DELETE http://localhost:4000/api/task/1
