GET http://localhost:4000/api/task

####

POST http://localhost:4000/api/task
Content-Type: application/json

{
  "title": "Descongelar el pollo",
  "description": "Descripción de la nueva tarea",
  "isComplete": false,
  "user_id": 1
}
####
PUT http://localhost:4000/api/task/11
Content-Type: application/json

{
  "title": "Tarea dsaasdsasadddlizada",
  "description": "Descripción actualizada de la tarea",
  "isComplete": true
}
####
GET http://localhost:4000/api/task/4

####
DELETE http://localhost:4000/api/task/2
