get http://localhost:4000/api/profiles

####
post http://localhost:4000/api/profiles
Content-Type: application/json

{
  "real_name": "Descongelar el pollo",
  "bio": "Descripción de la nueva tarea",
  "birthdate": "2023-10-01"
}

