####
get http://localhost:4000/api/labels

####
get http://localhost:4000/api/labels/1
####
POST http://localhost:4000/api/labels
Content-Type: application/json

{
    "name_Label": "urgente"
}

####
DELETE http://localhost:4000/api/labels/1
